### PR TITLE
JENKINS-61113 Fixed build number reset for Jenkins pipelines.

### PR DESCRIPTION
**Pull request by Jeykey1990**

### CODE REVIEW

**Comment by Jeykey1990** [comment]
I had a workaround checked into my Jenkinsfile. Looks like this does not work.

**Comment by maniax89** [comment]
@plavc when will this change be released? or has it already been released?

**Comment by bhartshorn** [comment]
@plavc just wanted to check in. I see you made a 1.0.2 release here on Github with this change, but it doesn't show in the Jenkins plugin repository. 

Are you planning to release there soon also?

Thanks for maintaining this plugin.

**Comment by plavc** [comment]
Somehow a snapshot instead of release version was pushed to Artifactory. I made a new release today. At this time it's still not available for download through Jenkins Plugins, but you can download hpi from here: 
https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/General/releases/net/plavcak/jenkins/scmskip/1.0.2

**Pull request merged**
