### PR TITLE
JENKINS-70507 fixed

### PR DESCRIPTION
**Pull request by camueller**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira

This PR fixes https://issues.jenkins.io/browse/JENKINS-70507

It only skips the build if all commits match the skip pattern.

The plugin developer does not seem to be active anymore. Therefore I build the plugin for myself (and possibly others) including the changes of this PR. You may download it from
https://drive.google.com/file/d/13iT2Br_OCk9SXjVZlQYCwwAlg4Z95188/view?usp=share_link

### CODE REVIEW

**Comment by NotMyFault** [comment]
Hey @camueller, while I was modernizing the plugin, I noticed your PR breaks current test cases. Would you mind taking a look and placing adjustments, where needed, please?

Thanks in advance!

**Comment by camueller** [comment]
If you are modernizing the plugin I would assume that my PR is not needed anymore. I have no problem with that as long as the plugin works :-)

**Comment by NotMyFault** [comment]
> If you are modernizing the plugin I would assume that my PR is not needed anymore. I have no problem with that as long as the plugin works :-)

Modernization covers adopting latest infrastructure related changes and miscellaneous dependency updates. I'm not touching the code base outside of pre-existing PRs.

**Comment by zbynek** [comment]
@NotMyFault unless I'm missing something this is identical to https://github.com/jenkinsci/scmskip-plugin/pull/7 that you already merged & released (?)

**Comment by NotMyFault** [comment]
> @NotMyFault unless I'm missing something this is identical to #7 that you already merged & released (?)

Looks like it

**Pull request closed without merging**
